FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 7168

ENV ASPNETCORE_URLS=http://+:7168

# Grant write permissions to /app before dropping privileges
RUN mkdir -p /app && chmod -R 777 /app

USER app
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG configuration=Release
WORKDIR /src
COPY ["GRPCService/GRPCService/GRPCService.csproj", "GRPCService/"]
RUN dotnet restore "GRPCService/GRPCService.csproj"
COPY . .
WORKDIR "/src/GRPCService"
RUN dotnet build "GRPCService/GRPCService.csproj" -c $configuration -o /app/build



FROM build AS publish
ARG configuration=Release
RUN dotnet publish "GRPCService/GRPCService.csproj" -c $configuration -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "GRPCService.dll"]