FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 5270

ENV ASPNETCORE_URLS=http://+:5270

# Grant write permissions to /app before dropping privileges
RUN mkdir -p /app && chmod -R 777 /app

USER app
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG configuration=Release
WORKDIR /src
COPY ["ApIService/ApIService/ApIService.csproj", "ApIService/"]
RUN dotnet restore "ApIService/ApIService.csproj"
COPY . .
WORKDIR "/src/ApIService"
RUN dotnet build "ApIService/ApIService.csproj" -c $configuration -o /app/build

FROM build AS publish
ARG configuration=Release
RUN dotnet publish "ApIService/ApIService.csproj" -c $configuration -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ApIService.dll"]